spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Books_library
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update  # Опции: none, validate, update, create, create-drop
      show-sql: true  # Показывать SQL-запросы в консоли
    properties:
      current_session_context_class: thread  # Контекст сессии

# Дополнительные настройки
logging:
  level:
    org.hibernate.SQL: DEBUG  # Уровень логирования для SQL-запросов