server:
  port: 8084

spring:
  application:
    name: user-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: user-service
        health-check:
          enabled: false  # Отключить проверки состояния
      config:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/Books_library_users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

jwt:
  expiration-time: 3600000  # 60 минут в миллисекундах
